Web/nxweb/js/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

# namespace
app_name = 'js'

urlpatterns = [
    #path('', views.index, name = 'home'),
    #path('aj/', views.load_cities, name ='ld'),
    #path('add/'), views.personcreate, name = 'add'),
    # 创建新客户
    re_path(r'^client/create/$', views.ClientCreateView.as_view(), name='client_create'),

    # 显示客户详情
    re_path(r'^client/(?P<pk>\d+)/$', views.ClientDetailView.as_view(), name='client_detail'),

    # Ajax调用城市清单
    re_path(r'^ajax/load_cities/$', views.ajax_load_cities, name='ajax_load_cities'),

       

]

Web/nxweb/nxweb/urls.py
from django.contrib import admin
from django.urls import path, include
import ipam.views as ipam_views
import ipam.urls
import js.urls

urlpatterns = [
    path('admin/', admin.site.urls),      
    path('ipam/', include(ipam.urls)),
    path('', ipam_views.index, name = 'home'),
    path('js/', include(js.urls)),
]

Web/nxweb/js/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Country(models.Model):

    name = models.CharField(verbose_name="country", max_length=50)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(verbose_name="city", max_length=50)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="country",)

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(verbose_name="client", max_length=50)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, verbose_name="country")
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name="city")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dropdown:client_detail', kwargs={'pk': self.pk})

Web/nxweb/js/forms.py
from django import forms
from js.models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["name", "country", "city"]

Web/nxweb/js/views.py
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from .models import Client, City
from .forms import ClientForm
from django.http import JsonResponse


# Create your views here.！



class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'client_form.html'


class ClientDetailView(DetailView):
    model = Client

def ajax_load_cities(request):
    if request.method == 'GET':
        country_id = request.GET.get('country_id', None)
        if country_id:
            data = list(City.objects.filter(country_id=country_id).values("id", "name"))
            return JsonResponse(data, safe=False)

Web/nxweb/js/templates/client_form.html
{% block content %}
<h2>创建用户 - 联动下拉菜单</h2>
<form method="post" class="form-horizontal" role='form' action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
    $("#id_country").change(function() {
      var country_id = $(this).val();

      $.ajax({
        url: '/js/ajax/load_cities/',
        data: {
          'country_id': country_id
        },
        type: 'GET',
        dataType: 'json',
        success: function (data) {
            var content='';
            $.each(data, function(i, item){
                  content+='<option value='+item.id+'>'+item.name+'</option>'
                });
            $('#id_city').html(content)
        },

      });
    });
  </script>

Web/nxweb/js/templates/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>W3Cschool在线教程(w3cschool.cn)</title> 
<script>
var x = 16 + "22"
function ChangeText(){
    document.getElementById('demo1').innerHTML = x
}
alert(x)
</script>
</head>
<body>

<h1>我的第一个 JavaScript 程序</h1>
<p id="demo">这是一个段落</p>
<text id='demo1'>hello</text>

<button type="button" onclick="ChangeText()">显示日期</button>

</body>
</html>